config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students, :controllers => {:registrations => "student_registrations", :sessions => "student_sessions"}
  devise_scope :student do
    get '/student/index', to: 'student#index', as: 'student_root'
  end
  devise_for :tutors
  devise_scope :tutor do
    get 'tutors', to: 'members#index', as: 'tutor_root'
  end
  root 'home#index'
  # student_root_path 'student#index'
  # tutor_root_path 'tutor#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'restricted', to: 'home#restricted', as: 'restricted'
  get 'about_us', to: 'home#about_us', as: 'about_us'


  get 'tutors', to: 'members#index', as: 'tutors'
  get '/tutors/profile_form', to: 'members#profile_form', as: 'profile_form'
  get '/tutors/bookings/', to: 'members#bookings', as: 'tutor_bookings'
  post '/tutors/profile_create', to: 'members#profile_create'
  patch '/tutors/profile', to: 'members#profile', as: 'profile'
  patch '/tutors/update_subjects', to: 'members#update_subjects', as: 'update_subjects'
  post '/tutors/create_subjects', to: 'members#create_subjects', as: 'create_subjects'
  delete '/tutors/destroy_subject', to: 'members#destroy_subject', as: 'destroy_subject'

  get 'students', to: 'student#index', as: 'students'
  get 'students/join/', to: 'student#join', as: 'students_join'
  get 'students/search/', to: 'student#search', as: 'search'
  get 'students/tutor_profile/:id', to: 'student#tutor_profile', as: 'student_tutor_profile'
  get 'students/favourite/:id', to: 'student#favourite', as: 'favourite'
  post 'students/make_booking/', to: 'student#make_booking'
  get 'students/bookings/', to: 'student#bookings', as: 'student_bookings'
  get 'students/booking_page/', to: 'student#booking_page', as: 'booking_page'
  get 'students/success', to: 'student#success'
  # match '*path' => 'home#index', via: [:get, :post]
  # match "*path", to: redirect('/'), via: :all
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites
  has_many :bookings
  has_many :tutors, through: :favourites
  has_one :tutor, through: :bookings
  has_one :payment, through: :bookings

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:make_booking]
    before_action :authenticate_student!, except: [:make_booking]
    

    def index
        # default page after login, shows the search form
        @@student_id = Student.find(current_student.id).id
        country_codes = []
        state_codes = []
        subjects = []
        Tutor.all.each do |tutor|
            country_codes << [tutor.country.upcase,tutor.country.upcase]
            state_codes << [tutor.state.upcase,tutor.state.upcase]
        end
        subject_array_unsorted = Subject.all
        subject_array_sorted = subject_array_unsorted.sort_by{ |object| object[:title].downcase }
        subject_array_sorted.each do |subject_name|
            subjects << [subject_name.title.downcase,subject_name.title.downcase]
        end
        @country_codes = country_codes.uniq.sort
        @country_codes.unshift(["", ""])
        @state_codes = state_codes.uniq.sort
        @state_codes.unshift(["", ""])
        @subjects = subjects.uniq
        @subjects.unshift(["", ""])
    end
    def search
        # processes search request
        params.permit(:firstname, :lastname, :country, :state, :subject, :available)
        if params[:firstname] == '' and params[:lastname] == '' and params[:country] == '' and params[:state] == '' and params[:subject] == '' and ( params[:available] == '0' or params[:available] == '1')
            message = "⚠️ #{160.chr("UTF-8")} Please select or enter something to search"
            flash[:alert] = message
            redirect_to request.referer
        end
        if params[:subject] != ''
            tutor_join_subject_match = Tutor.joins(:subjects).where('lower(title) LIKE ?', "%#{params[:subject].downcase}%")
            @tutors = tutor_join_subject_match
            if params[:available] == '1'
                subject_hours_match = tutor_join_subject_match.where("time > ?", 0)
                @tutors = subject_hours_match
            end
            if params[:state] != ''
                @tutors = @tutors.where('lower(state) LIKE ?', "%#{params[:state].downcase}%")
            end
            if params[:country] != ''
                @tutors = @tutors.where('lower(country) LIKE ?', "%#{params[:country].downcase}%")
            end
        else
            case
            when params[:firstname] != '', params[:lastname] == ''
                @tutors = Tutor.where('lower(firstname) LIKE ?', "%#{params[:firstname].downcase}%")
                if params[:state] != ''
                    @tutors = @tutors.where('lower(state) LIKE ?', "%#{params[:state].downcase}%")
                end
                if params[:country] != ''
                    @tutors = @tutors.where('lower(country) LIKE ?', "%#{params[:country].downcase}%")
                end
            when params[:firstname] != '', params[:lastname] != ''
                @tutors = Tutor.where('lower(firstname) LIKE ?', "%#{params[:firstname].downcase}%")
                @tutors = @tutors.where('lower(lastname) LIKE ?', "%#{params[:lastname].downcase}%")
            when params[:firstname] == '', params[:lastname] != ''
                @tutors = Tutor.where('lower(lastname) LIKE ?', "%#{params[:lastname].downcase}%")
                if params[:state] != ''
                    @tutors = @tutors.where('lower(state) LIKE ?', "%#{params[:state].downcase}%")
                end
                if params[:country] != ''
                    @tutors = @tutors.where('lower(country) LIKE ?', "%#{params[:country].downcase}%")
                end
            else
                case
                when params[:state] != '', params[:country] == ''
                    @tutors = Tutor.where('lower(state) LIKE ?', "%#{params[:state].downcase}%")
                when params[:state] == '', params[:country] != ''
                    @tutors = Tutor.where('lower(country) LIKE ?', "%#{params[:country].downcase}%")
                else
                    @tutors = Tutor.where('lower(state) LIKE ?', "%#{params[:state].downcase}%")
                    @tutors = @tutors.where('lower(country) LIKE ?', "%#{params[:country].downcase}%") 
                end 
            end
        end
    end

    def tutor_profile
        # show tutor profile
        @tutor = Tutor.find_by_id(params[:id])
        @tutor_profile = Profile.find_by(tutor_id: params[:id])
        @exists = current_student.favourites.find_by(tutor_id: params[:id])
        @subjects = @tutor.subjects.all
    end

    def favourite
        # processes favouriting and unfavouriting of tutors
        params.permit(:id, :remove)
        tutor_object = Tutor.find_by_id(params[:id])
        tutor_fullname = tutor_object.firstname.capitalize + " " + tutor_object.lastname.capitalize
        exists = current_student.favourites.find_by(tutor_id: params[:id])
        remove = params[:remove]
        if exists and remove
            record = current_student.favourites.find_by_tutor_id(params[:id])
            record.destroy
            flash[:alert] = "#{tutor_fullname} has been removed from favourites"
        elsif
            flash[:alert] = "#{tutor_fullname} is already in favourites"
        end
        
        if !exists
            current_student.favourites.create(tutor_id: params[:id])
            flash[:alert] = "😍  #{160.chr("UTF-8")}#{160.chr("UTF-8")}#{160.chr("UTF-8")}#{tutor_fullname} was added to favourites "
        end
        redirect_to request.referer
    end
    def make_booking
        # processes the webhook json from stripe
        tx_id = params[:data][:object][:id]
        subject_id = params[:data][:object][:charges][:data][0][:metadata][:subject_id].to_i
        tutor_id = params[:data][:object][:charges][:data][0][:metadata][:tutor_id].to_i
        subject = Subject.find(subject_id)
        student = Student.find(@@student_id)

        # action: make a booking and a payment and update the hours for the tutor's subject

        if subject.time > 0
            booking = student.bookings.create(tutor_id: tutor_id, time: 1, subject_id: subject_id)

            # create the payment using hard coded amount of $60 per hour
            payment = Payment.create(amount: 60, booking_id: booking.id)
            # Decrement the number of hours for the tutor's subject
            
            new_subject_hours = subject.time - 1
            subject.update(time: new_subject_hours)
            # flash[:alert] = "You just made a booking!"
            # redirect_to request.referer
        else
            # fail
            print "ALERT*************************************FAILED!!!!!"
        end

    end

    def booking_page
        # the cart page where the stripe session is set
        params.permit(:subject, :tutor)
        tutor_id = params[:tutor].to_i
        subject_id = params[:subject].to_i
        subject = Subject.find(subject_id)
        tutor = Tutor.find(tutor_id)
        student_id = current_student.id
        @tutor_fullname = tutor.firstname + ' ' + tutor.lastname
        description = "1 hour of professional tutoring with " + @tutor_fullname
        name = "Subject: " + subject.title.capitalize
        @subject_title = subject.title
        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: 'graycode+stripe@protonmail.com',
            line_items: [{
                name: name,
                description: description,
                images: ['https://res.cloudinary.com/glenfish/image/upload/sr2xeymu1glcpl6bv8w7v7e411js.png'],
                amount: 6000,
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    subject: @subject_title,
                    tutor: @tutor_fullname,
                    subject_id: subject_id,
                    tutor_id: tutor_id,
                    student_id: student_id,
                }
            },
            success_url: "#{root_url}students/success",
            cancel_url: "#{root_url}students"
        )
        @session_id = session.id
        

    end

    def success
        # shown after successful stripe checkout

    end


    def bookings
        # shows all bookings a student has successfully paid for
        @bookings = current_student.bookings.all
    end
end

app/helpers/student_helper.rb
module StudentHelper
    def is_favourited(id)
        return current_student.favourites.find_by(tutor_id: id)
    end

    def get_student_booking_info(booking)
        booking_info = ""
        subject = Subject.find(booking.subject_id)
        subject_title = subject.title.capitalize
        booked_time = booking.time
        booking_amount = "$#{Payment.find_by(booking_id: booking.id).amount}.00"
        case booked_time
        when 1
            booked_time = "#{booked_time} hour"
        else
            booked_time = "#{booked_time} hours"
        end
        tutor = Tutor.find(booking.tutor_id)
        tutor_name = tutor.firstname + ' ' + tutor.lastname
        tutor_email = tutor.email

        booking_info = "<div class='card' style='width: 18rem;'><div class='card-body'><h5 class='card-title'>Booking ID: "
        booking_info << booking.id.to_s
        booking_info << "</h5><h6 class='card-subtitle mb-2 text-muted'>"
        booking_info << booking.created_at.strftime('%d/%m/%Y').to_s
        booking_info << "</h6><p class='card-text'>Tutor: "
        booking_info << tutor_name
        booking_info << "<br>Subject: "
        booking_info << subject_title
        booking_info << "<br>Time: "
        booking_info << booked_time>to_s
        booking_info << "<br>Paid: "
        booking_info << booking_amount.to_s
        booking_info << "<br>Tutor Contact: "
        booking_info << tutor_email
        booking_info << "<br><br><a href="
        booking_info << student_tutor_profile_path(booking.tutor_id)
        booking_info << " class='btn btn-primary btn-sm'>View Profile</a>"
        booking_info << "</p></div></div>"
        


        return booking_info
    end
end

app/views/student/booking_page.html.erb
<% call_to_action = "Purchase 1 hour of tutoring".upcase %>
<div class="jumbotron jumbotron-fluid" id="jumbo">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= call_to_action %></h4>
      </div>
      <div class="modal-body">
      <img src="https://res.cloudinary.com/glenfish/image/upload/zjwfkqx67md7gsx784mcz8tarb67.png" alt="tick" class='success-tick' style="width:72px; float:left; margin-right: 30px;">
        <p>Tutor name: <%= @tutor_fullname %><br>
		Subject: <%= @subject_title.capitalize %><br>
		Price: $60.00<br>
		</p>
      </div>
      <div class="modal-footer">
        <button data-stripe="payment" class="btn btn-primary btn-lg">Go To Checkout</button><br><br>

      </div>
    </div>
  </div>
</div>


<script src="https://js.stripe.com/v3/"></script>

<script>
	document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
		const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
		stripe.redirectToCheckout({
			sessionId: "<%= @session_id %>"
		});
	});
</script>

app/views/student/bookings.html.erb
<h1>Bookings</h1>
<br>
<% if @bookings.exists? %>
    <% booking_array = [] %>
    <% all_bookings_formatted = "" %>
    <% @bookings.reverse.each do |booking| %>
    <% tutor = Tutor.find(booking.tutor_id) %>
        <% all_bookings_formatted << "#{get_student_booking_info(booking)}" %>
        <% all_bookings_formatted << "<br><hr><br>" %>
        
    <% end %>
    <%= sanitize all_bookings_formatted %>
    
<% else %>
        <p>You have no bookings.</p>
<% end %>

app/views/student/index.html.erb
<div>
<h4><%= current_student.firstname.capitalize %>, find your perfect Tutor!</h4>
</div>

<%= form_with url: search_path, method: :get do |form| %>

  <%= form.label :subject %><br>
  <%= form.select :subject, @subjects,  {}, {class: "form-select mb-2 w-50"}%>
  <div id="search-checkbox">
  <%= form.check_box :available, class: "form-check-input form-control form-check-inline mb-4 mycheckbox" %>
  <%= form.label "Available hours only", class: "pad-top" %> 
 </div>

  <%= form.label :country %><br>
  <%= form.select :country, @country_codes,  {}, {class: "form-select mb-1 w-25"} %><br>

  <%= form.label :state %><br>
  <%= form.select :state, @state_codes,  {}, {class: "form-select mb-1 w-25"} %><br>

  <%= form.label "First Name" %><br>
  <%= form.text_field :firstname, class: "form-control w-25 mb1"%><br>
  <%= form.label "Last Name" %><br>
  <%= form.text_field :lastname, class: "form-control w-25 mb1" %><br>
  <%= form.submit "Find A Tutor", class: "btn btn-primary btn-lg" %>
<% end %>
<br><br>

app/views/student/search.html.erb
<h1>Search Results</h1>
<% if @tutors != [] and !@tutors.nil? %>
    <% @tutors.each do |tutor| %>
        <div class="tutor_fave_container">
            <div class="card">
                <div class="card-header">
                
            </div>
            <div class="card-body">
                <h5 class="card-title">Name: <%= tutor.firstname ? tutor.firstname.capitalize : 'none' %>
            <%= tutor.lastname.capitalize %></h5>
                <%# <p class="card-text">Email contact will be revealed after booking</p> %>
                <% if tutor.profile.photo.url %>
                    <%= cl_image_tag tutor.profile.photo.url , class: 'tutor_fave_pic', :width => 130, :crop => "pad", cloud_name: $cloud_name %>
                <% end %>
                Email: <%= tutor.email.downcase.sub(/\A(.)(.*)(...)\z/) {|m| $1 + ("*" * $2.length) + $3 } %><br>
            State: <%= tutor.state.upcase %><br>
            Country: <%= tutor.country.upcase %><br><br>
            <%= link_to 'View Profile', student_tutor_profile_path(tutor), class: "btn btn-primary btn" %><br><br>
            <% is_favourited(tutor.id) ? exists = true : exists = false %>
            <% if !exists %>
                <%= link_to "add to favourites", favourite_path(tutor.id), class: "btn btn-sm btn-outline-success" %> &nbsp;&nbsp;
            <% else %>
                <%= link_to "remove from favourites", {controller: "student", action: "favourite", id: tutor.id, remove: true}, class: "btn btn-sm btn-outline-secondary" %> &nbsp;&nbsp;
            <% end %>
            </div>
        </div><br>
    <% end %>
<% else %>
    <h4>Nothing matched your search</h4>
    <%= link_to "back", request.referer.present? ? request.referer : default_path %>
<% end %>

app/views/student/success.html.erb
<div class="jumbotron jumbotron-fluid" id="jumbo">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
<h1>Order Success!</h1>

<img src="https://res.cloudinary.com/glenfish/image/upload/dwwxws13jivyz5iur2tiepa9yxrg.jpg" alt="tick" class='success-tick' style="width:100px; float:left; margin-right: 30px;">


</div>
<p><br>&nbsp Thank you for your purchase.
<%= link_to "View Your Booking", student_bookings_path %>
<br>
</p>
</div>
</div>
</div>

app/views/student/tutor_profile.html.erb
<h1><%= @tutor.firstname %> <%= @tutor.lastname %></h1>
<% if !@exists %>
    <%= link_to "add to favourites", favourite_path(@tutor.id), class: "btn btn-sm btn-outline-success" %> &nbsp;&nbsp;
<% else %>
<%= link_to "remove from favourites", {controller: "student", action: "favourite", id: @tutor.id, remove: true}, class: "btn btn-sm btn-outline-secondary" %> &nbsp;&nbsp;
<% end %><%= link_to "back", request.referer.present? ? request.referer : default_path, class: "btn btn-sm btn-outline-secondary" %><br><br><br>
<% if @tutor_profile %>
    <% if @tutor.profile.photo.url %>
        <%= cl_image_tag @tutor.profile.photo.url, class: 'profile_image_main', cloud_name: $cloud_name %>
    <% end %>
    <h3><%= @tutor_profile.title %></h3>
    <p>
    <%= @tutor.profile.description %><br><br>
    
    <h6>State: <%= @tutor.state.upcase%></h6>
    <h6>Country: <%= @tutor.country.upcase%></h6><br><br>
    <% if @subjects.first %>
        <% @subjects.each do |subject| %>
        <% subject.time > 0 ? time_available = true : time_available = false %>
        <div class="subject-row">
            <div class="jumbotron-fluid">
                <div class="container-fluid">
                <h4 class="display-6"><%= subject.title.upcase %></h4>
                <p class="lead">Hours available: &nbsp;<span class="bold"><%= subject.time %></span><br>
                <% if time_available %>
                    <%= button_to "Book Time", booking_page_path, method: :get, params: { subject: subject.id, tutor: @tutor.id }, class: "btn btn-primary btn" %>
                    <hr class="my-4">
                <% else %>
                    <hr class="my-4">
                <% end %>
                </p>
                </div>
            </div>
        </div>
        <% end %>
    <% else %>
        <br><h4><%= @tutor.firstname %> is not actively tutoring at this time</h4>
        <% end %>
    </p>
<% else %>
    <p>There is no profile for this Tutor yet</p>
<% end %>
<% if !@exists %>
    <%= link_to "add to favourites", favourite_path(@tutor.id), class: "btn btn-sm btn-outline-success" %> &nbsp;&nbsp;
<% else %>
    <%= link_to "remove from favourites", {controller: "student", action: "favourite", id: @tutor.id, remove: true}, class: "btn btn-sm btn-outline-secondary" %> &nbsp;&nbsp;
<% end %>
<%= link_to "back", request.referer.present? ? request.referer : default_path, class: "btn btn-sm btn-outline-secondary" %>
<br><br>