config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students, :controllers => {:registrations => "student_registrations", :sessions => "student_sessions"}
  devise_scope :student do
    get '/student/index', to: 'student#index', as: 'student_root'
  end
  devise_for :tutors
  devise_scope :tutor do
    get 'tutors', to: 'members#index', as: 'tutor_root'
  end
  root 'home#index'
  # student_root_path 'student#index'
  # tutor_root_path 'tutor#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'restricted', to: 'home#restricted', as: 'restricted'
  get 'about_us', to: 'home#about_us', as: 'about_us'


  get 'tutors', to: 'members#index', as: 'tutors'
  get '/tutors/profile_form', to: 'members#profile_form', as: 'profile_form'
  get '/tutors/bookings/', to: 'members#bookings', as: 'tutor_bookings'
  post '/tutors/profile_create', to: 'members#profile_create'
  patch '/tutors/profile', to: 'members#profile', as: 'profile'
  patch '/tutors/update_subjects', to: 'members#update_subjects', as: 'update_subjects'
  post '/tutors/create_subjects', to: 'members#create_subjects', as: 'create_subjects'
  delete '/tutors/destroy_subject', to: 'members#destroy_subject', as: 'destroy_subject'

  get 'students', to: 'student#index', as: 'students'
  get 'students/join/', to: 'student#join', as: 'students_join'
  get 'students/search/', to: 'student#search', as: 'search'
  get 'students/tutor_profile/:id', to: 'student#tutor_profile', as: 'student_tutor_profile'
  get 'students/favourite/:id', to: 'student#favourite', as: 'favourite'
  post 'students/make_booking/', to: 'student#make_booking'
  get 'students/bookings/', to: 'student#bookings', as: 'student_bookings'
  get 'students/booking_page/', to: 'student#booking_page', as: 'booking_page'
  get 'students/success', to: 'student#success'
  # match '*path' => 'home#index', via: [:get, :post]
  # match "*path", to: redirect('/'), via: :all
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to image_tag("https://i.imgur.com/N5yZNK2.png?1", border: 0), {action: 'index', controller: '/home'}, {class: 'navbar-brand'} %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll">
      <% if (!student_signed_in? && !tutor_signed_in?)%>
        <li class="nav-item">
          <%= link_to "About",  about_us_path, class: 'nav-link active px-4 navbar-brand' %>
        </li>
        <%# <li class="nav-item dropdown"> %>
          <%# <span class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Login</span> %>
          <%# <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown"> %>
            <li><%= link_to "Tutor Login",  tutor_session_path, class: 'nav-link active px-4 navbar-brand' %></li>
            <li><%= link_to "Student Login",  student_session_path, class: 'nav-link active px-4 navbar-brand' %></li>
          <%# </ul> %>
        <%# </li> %>
      <% end %>
      <% if student_signed_in? %> 
        <li class="nav-item">
          <%= link_to "Favourite Tutors",  restricted_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings",  student_bookings_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
      <% end %>
        <% if tutor_signed_in? %>
        <li class="nav-item">
          <%= link_to "Bookings",  tutor_bookings_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <li class="nav-item">
          <%= link_to "Subjects",  restricted_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <% end %>
        <% if tutor_signed_in? %>
        <li class="nav-item">
          <%= link_to "Profile",  tutors_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <li class="nav-item">
          <%= link_to "About",  about_us_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <% end %>
        <% if student_signed_in? %>
        <li class="nav-item">
          <%= link_to "Tutor Search",  students_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <li class="nav-item">
          <%= link_to "About",  about_us_path, class: 'nav-link active px-3 navbar-brand' %>
        </li>
        <% end %>
        <% if (student_signed_in? || tutor_signed_in?)%>
        <li class="nav-item">
          <%= link_to "Logout",  destroy_tutor_session_path, class: 'nav-link active px-3 navbar-brand', method: 'delete' %>
        </li>
      <% end %>
      </ul>  
    </div>
  </div>
</nav>

app/views/shared/_navbar_old.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to image_tag("https://i.imgur.com/N5yZNK2.png?1", border: 0), {action: 'index', controller: '/home'}, {class: 'navbar-brand'} %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if (!student_signed_in? && !tutor_signed_in?)%>
        <li class="nav-item">
          <%= link_to "Tutor Login",  tutor_session_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "Student Login",  student_session_path, class: 'nav-link active' %>
        </li>
      <% end %>
      <% if student_signed_in? %> 
        <li class="nav-item">
          <%= link_to "Favourite Tutors",  restricted_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings",  student_bookings_path, class: 'nav-link active' %>
        </li>
      <% end %>
        <% if tutor_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Subjects",  restricted_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings",  tutor_bookings_path, class: 'nav-link active' %>
        </li>
        <% end %>
        <% if tutor_signed_in? %>
        <li class="nav-item">
          <%= link_to "Tutor Central",  tutors_path, class: 'nav-link active' %>
        </li>
        <% end %>
        <% if student_signed_in? %>
        <li class="nav-item">
          <%= link_to "Tutor Search",  students_path, class: 'nav-link active' %>
        </li>
        <% end %>
        <% if (student_signed_in? || tutor_signed_in?)%>
        <li class="nav-item">
          <%= link_to "Logout",  destroy_tutor_session_path, class: 'nav-link active', method: 'delete' %>
        </li>
        <% end %>
        

      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>