config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students, :controllers => {:registrations => "student_registrations", :sessions => "student_sessions"}
  devise_scope :student do
    get '/student/index', to: 'student#index', as: 'student_root'
  end
  devise_for :tutors
  devise_scope :tutor do
    get 'tutors', to: 'members#index', as: 'tutor_root'
  end
  root 'home#index'
  # student_root_path 'student#index'
  # tutor_root_path 'tutor#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'restricted', to: 'home#restricted', as: 'restricted'
  get 'about_us', to: 'home#about_us', as: 'about_us'


  get 'tutors', to: 'members#index', as: 'tutors'
  get '/tutors/profile_form', to: 'members#profile_form', as: 'profile_form'
  get '/tutors/bookings/', to: 'members#bookings', as: 'tutor_bookings'
  post '/tutors/profile_create', to: 'members#profile_create'
  patch '/tutors/profile', to: 'members#profile', as: 'profile'
  patch '/tutors/update_subjects', to: 'members#update_subjects', as: 'update_subjects'
  post '/tutors/create_subjects', to: 'members#create_subjects', as: 'create_subjects'
  delete '/tutors/destroy_subject', to: 'members#destroy_subject', as: 'destroy_subject'

  get 'students', to: 'student#index', as: 'students'
  get 'students/join/', to: 'student#join', as: 'students_join'
  get 'students/search/', to: 'student#search', as: 'search'
  get 'students/tutor_profile/:id', to: 'student#tutor_profile', as: 'student_tutor_profile'
  get 'students/favourite/:id', to: 'student#favourite', as: 'favourite'
  post 'students/make_booking/', to: 'student#make_booking'
  get 'students/bookings/', to: 'student#bookings', as: 'student_bookings'
  get 'students/booking_page/', to: 'student#booking_page', as: 'booking_page'
  get 'students/success', to: 'student#success'
  # match '*path' => 'home#index', via: [:get, :post]
  # match "*path", to: redirect('/'), via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :auth_is_logged_in, only: [:restricted]

    def index
    end
    def restricted
        # shows student's favourited tutors
        if student_signed_in?
            @favourited = current_student.favourites
            favourited_tutors_array = []
            @favourited.each do |fave|
            print "*******************Favourited: #{fave.tutor.id}"
            tutor = Tutor.find_by_id(fave.tutor.id)
            favourited_tutors_array << tutor
            end
            @tutors = favourited_tutors_array
        end
    end

    private


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_subjects_form.html.erb
<% if @subjects.first %>
<p>Below are all the subjects you have listed. You can update the hours on any subject below or <a href="#new-subject">add a new subject</a> </p>
    <% @subjects.each do |subject| %>
        <%= form_with model: @subject, url: update_subjects_path, method: "patch" do |form| %>
        <%= form.hidden_field :id, value: subject.id %>
        <%= form.label "Subject" %><br>
        <%= form.text_field :title, value: subject.title, :required => true, class: "form-control w-25 mb1"  %><br>
        <%= form.label "Hours offered this month" %><br>
        <%= form.number_field :time, in: 0..100, step: 1, value: subject.time, :required => true, class: "form-control w-25 mb1"  %><br>
        <%= form.submit class: "btn btn-success" %>
        <% end %><hr>
    <% end %>
    <a name="new-subject"></a>
    <h4>Add New Subject:</h4>
    <%= form_with model: @subject, url: create_subjects_path do |form| %>
        <%= form.label "Subject" %><br>
        <%= form.text_field :title, :required => true, class: "form-control w-25 mb1"  %><br>
        <%= form.label "Hours offered this month" %><br>
        <%= form.number_field :time, in: 0..100, step: 1, :required => true, class: "form-control w-25 mb1"  %><br>
        <%= form.submit class: "btn btn-success" %>
    <% end %><hr>
<% else %>
    <p>Add Subject and Tutoring Hours</p>
    <%= form_with model: @subject, url: create_subjects_path do |form| %>
        <%= form.label "Subject" %><br>
        <%= form.text_field :title, :required => true, class: "form-control w-25 mb1"  %><br>
        <%= form.label "Hours offered this month" %><br>
        <%= form.number_field :time, in: 0..100, step: 1, :required => true, class: "form-control w-25 mb1"  %><br><br>
        <%= form.submit class: "btn btn-success" %>
    <% end %><br>
<% end %>

app/views/home/about_us.html.erb
<h1>About Us</h1>
<p>This app is a two-sided marketplace matching students with tutors.</p>

<p>Tutors can create a profile and list subjects they teach.</p>

<p>Students can search for tutors teaching subjects of interest, and book tutoring time.</p>

<p>Secure credit card payment processing is provided by Stripe.com.
</p>

<p>A service that brings together teaching talent and those who have a need for one-on-one training is always valuable. Students at university, community college, self-studying or doing bootcamps all can benefit from finding the perfect tutor who can help their learning journey.</p>

<p>This app is simple to use and with a very short time commitment, a student and tutor can be in touch and having an online Zoom meeting, or Skype call. Once a successful payment and booking has been made, both parties are given their other's contact information.</p>

<p>Note: This app is currently in alpha and payments are running in test mode on the live app. Tutor rate is hard coded at AUD$60 per hour.</p>

<p>TutorMe developed by <a href="https://github.com/glenfish" target="_blank">glenfish</a></p>

app/views/home/index.html.erb
<img src="https://res.cloudinary.com/glenfish/image/upload/rf79k2j91cjn2x183b0w6140z7qy.jpg" width="100%" class="hero-image">

app/views/home/restricted.html.erb
<% if tutor_signed_in? %>
    <h1>Subjects</h1>
    <%= render 'subjects_form', locals: @subject %>
    
<% end %>
<% if student_signed_in? %>
    <h2>My Favourite Tutors</h2>

    <% if @tutors != [] %>
        <% @tutors.each do |tutor| %>
        <div class="tutor_fave_container">

            <div class="card">
                <div class="card-header">
                
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= tutor.firstname ? tutor.firstname.capitalize : 'none' %> 
            <%= tutor.lastname.capitalize %></h5>
                <%# <p class="card-text">Email contact will be revealed after booking</p> %>
                <% if tutor.profile.photo.url %>
                    <%= cl_image_tag tutor.profile.photo.url , class: 'tutor_fave_pic', :width => 140, :crop => "pad", cloud_name: $cloud_name %>
                <% end %>
                <%= tutor.email.downcase.sub(/\A(.)(.*)(...)\z/) {|m| $1 + ("*" * $2.length) + $3 } %><br>
            <%= tutor.state.upcase %><br>
            <%= tutor.country.upcase %><br><br>
            <%= link_to 'View Profile', student_tutor_profile_path(tutor), class: "btn btn-primary btn" %><br><br>
            <%= link_to "remove from favourites", {controller: "student", action: "favourite", id: tutor.id, remove: true}, class: "btn btn-sm btn-outline-secondary" %>
            </div>
        </div>
        <br>
        <% end %>
    <% else %>
        <h4>You currently have no favourites selected</h4>
        <br>
        <%= link_to "back", request.referer.present? ? request.referer : default_path %>
    <% end %>

<% end %>