config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students, :controllers => {:registrations => "student_registrations", :sessions => "student_sessions"}
  devise_scope :student do
    get '/student/index', to: 'student#index', as: 'student_root'
  end
  devise_for :tutors
  devise_scope :tutor do
    get 'tutors', to: 'members#index', as: 'tutor_root'
  end
  root 'home#index'
  # student_root_path 'student#index'
  # tutor_root_path 'tutor#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'restricted', to: 'home#restricted', as: 'restricted'
  get 'about_us', to: 'home#about_us', as: 'about_us'


  get 'tutors', to: 'members#index', as: 'tutors'
  get '/tutors/profile_form', to: 'members#profile_form', as: 'profile_form'
  get '/tutors/bookings/', to: 'members#bookings', as: 'tutor_bookings'
  post '/tutors/profile_create', to: 'members#profile_create'
  patch '/tutors/profile', to: 'members#profile', as: 'profile'
  patch '/tutors/update_subjects', to: 'members#update_subjects', as: 'update_subjects'
  post '/tutors/create_subjects', to: 'members#create_subjects', as: 'create_subjects'
  delete '/tutors/destroy_subject', to: 'members#destroy_subject', as: 'destroy_subject'

  get 'students', to: 'student#index', as: 'students'
  get 'students/join/', to: 'student#join', as: 'students_join'
  get 'students/search/', to: 'student#search', as: 'search'
  get 'students/tutor_profile/:id', to: 'student#tutor_profile', as: 'student_tutor_profile'
  get 'students/favourite/:id', to: 'student#favourite', as: 'favourite'
  post 'students/make_booking/', to: 'student#make_booking'
  get 'students/bookings/', to: 'student#bookings', as: 'student_bookings'
  get 'students/booking_page/', to: 'student#booking_page', as: 'booking_page'
  get 'students/success', to: 'student#success'
  # match '*path' => 'home#index', via: [:get, :post]
  # match "*path", to: redirect('/'), via: :all
end

app/controllers/student_sessions_controller.rb
class StudentSessionsController < Devise::SessionsController
    def new
        self.resource = resource_class.new(sign_in_params)
    end
end

app/views/student_sessions/new.html.erb
<h6>Need an Account? <%= link_to "Signup", new_student_registration_path %></h6>
<h2>Student Login</h2>
<div class="form-container">
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control mb3" %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "current-password", class: "form-control mb3" %>
    </div>

    <% if devise_mapping.rememberable? %>
      <div class="field"><br>
        <%= f.check_box :remember_me, class: "form-check-input form-control form-check-inline mb-4 mycheckbox" %>
        <%= f.label :remember_me %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit "Log in", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>

  <%= render "devise/shared/links" %>
</div>